### ISSUE TITLE
双指快速向下滑动奔溃

### ISSUE THREAD

**Issue by Damon121** [anzaizai/EasyRefreshLayout#39]
单双指快速向下滑动时会出现奔溃现象，pointerIndex out of range  
具体错误日志如下：

` java.lang.IllegalArgumentException: pointerIndex out of range
                                                                  at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                  at android.view.MotionEvent.getX(MotionEvent.java:2032)
                                                                  at com.ajguan.library.EasyRefreshLayout.dispatchTouchEvent(EasyRefreshLayout.java:319)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2417)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2118)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2417)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2118)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2417)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2118)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2417)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2118)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2417)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2118)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2417)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2118)
                                                                  at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2552)
                                                                  at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1757)
                                                                  at android.app.Activity.dispatchTouchEvent(Activity.java:2861)
                                                                  at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                  at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2507)
                                                                  at android.view.View.dispatchPointerEvent(View.java:8700)
                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4518)
                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4380)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3864)
                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3917)
                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3883)
                                                                  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4000)
                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3891)
                                                                  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4057)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3864)
                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3917)
                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3883)
                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3891)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3864)
                                                                  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6397)
                                                                  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6338)
                                                                  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6309)
                                                                  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6578)
                                                                  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                  at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                  at android.os.MessageQueue.next(MessageQueue.java:143)
                                                                  at android.os.Looper.loop(Looper.java:122)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5372)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1125)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)`

**Comment by yihuiyu** [comment]
遇到了同样的问题 楼主解决了吗？

**Comment by hanilozmen** [comment]
The same problem is present for my app. Do you have any solutions/recommendations?
